poilist = {'后管': [{'id': 'B00190A5DK', 'parent': [], 'childtype': [], 'name': '后管', 'tag': [], 'type': '地名地址信息;普通地名;村庄级地名', 'typecode': '190108', 'biz_type': [], 'address': '六合区', 'location': '118.894084,32.425713', 'tel': [], 'postcode': [], 'website': [], 'email': [], 'pcode': '320000', 'pname': '江苏省', 'citycode': '025', 'cityname': '南京市', 'adcode': '320116', 'adname': '六合区', 'importance': [], 'shopid': [], 'shopinfo': '2', 'poiweight': [], 'gridcode': '4818571101', 'distance': [], 'navi_poiid': 'I50F043040_621', 'entr_location': [], 'business_area': [], 'exit_location': [], 'match': '0', 'recommend': '3', 'timestamp': [], 'alias': [], 'indoor_map': '0', 'indoor_data': {'cpid': [], 'floor': [], 'truefloor': [], 'cmsid': []}, 'groupbuy_num': '0', 'discount_num': '0', 'biz_ext': {'rating': [], 'cost': []}, 'event': [], 'children': [], 'photos': []}], '花园': [{'id': 'B00190D1IJ', 'parent': [], 'childtype': [], 'name': '龙海花园城', 'tag': [], 'type': '商务住宅;住宅区;住宅小区', 'typecode': '120302', 'biz_type': [], 'address': '园林东路101号', 'location': '118.858273,32.349763', 'tel': [], 'postcode': '211500', 'website': [], 'email': [], 'pcode': '320000', 'pname': '江苏省', 'citycode': '025', 'cityname': '南京市', 'adcode': '320116', 'adname': '六合区', 'importance': [], 'shopid': [], 'shopinfo': '0', 'poiweight': [], 'gridcode': '4818461821', 'distance': [], 'navi_poiid': 'I50F044039_2731', 'entr_location': '118.857928,32.348739', 'business_area': [], 'exit_location': [], 'match': '0', 'recommend': '0', 'timestamp': '2019-06-17 10:55:05', 'alias': [], 'indoor_map': '0', 'indoor_data': {'cpid': [], 'floor': [], 'truefloor': [], 'cmsid': []}, 'groupbuy_num': '0', 'discount_num': '0', 'biz_ext': {'rating': [], 'cost': '11564.00'}, 'event': [], 'children': [], 'photos': []}], '涧李': [{'id': 'B00190A5DT', 'parent': [], 'childtype': [], 'name': '涧李', 'tag': [], 'type': '地名地址信息;普通地名;村庄级地名', 'typecode': '190108', 'biz_type': [], 'address': '六合区', 'location': '118.892532,32.430192', 'tel': [], 'postcode': [], 'website': [], 'email': [], 'pcode': '320000', 'pname': '江苏省', 'citycode': '025', 'cityname': '南京市', 'adcode': '320116', 'adname': '六合区', 'importance': [], 'shopid': [], 'shopinfo': '2', 'poiweight': [], 'gridcode': '4818571111', 'distance': [], 'navi_poiid': 'I50F043040_628', 'entr_location': [], 'business_area': [], 'exit_location': [], 'match': '0', 'recommend': '3', 'timestamp': [], 'alias': [], 'indoor_map': '0', 'indoor_data': {'cpid': [], 'floor': [], 'truefloor': [], 'cmsid': []}, 'groupbuy_num': '0', 'discount_num': '0', 'biz_ext': {'rating': [], 'cost': []}, 'event': [], 'children': [], 'photos': []}]}




i = 0
for poi in poilist.keys():
    # 每一行写入
    print(poilist[poi][0]['id'])
    print(poilist[poi][0]['name'])
    i+=1
print()